const dataDemo = [{
    "name": "张三",
    "parent": "null",
    "children": [
        {
            "name": "李四",
            "parent": "张三",
            "children": [
                {
                    "name": "王五",
                    "parent": "李四",
                    "children": [
                        {"name": "程六", "parent": "王五"},
                        {"name": "王八", "parent": "王五"},
                        {"name": "王七", "parent": "王五"},
                        {
                            "name": "王九",
                            "parent": "王五",
                            "children": [
                                {"name": "王十", "parent": "王五"},
                                {"name": "王十一", "parent": "王五"},
                                {"name": "王十二", "parent": "王五"},
                                {"name": "王十三", "parent": "王五"},
                                {"name": "王十四", "parent": "王五"},
                                {
                                    "name": "程五",
                                    "parent": "王五",
                                    "children": [
                                        {"name": "程六", "parent": "程五"},
                                        {"name": "程七", "parent": "程五"},
                                        {"name": "程八", "parent": "程五"},
                                        {"name": "小张", "parent": "小红"},
                                        {"name": "小王", "parent": "小红"},
                                        {"name": "小程", "parent": "小红"},
                                        {"name": "小陈", "parent": "小红"},
                                        {"name": "小明", "parent": "小红"},
                                        {"name": "小张", "parent": "小红"},
                                        {"name": "小王", "parent": "小红"},
                                        {"name": "小程", "parent": "小红"},
                                        {"name": "小陈", "parent": "小红"},
                                        {"name": "小明", "parent": "小红"},
                                        {"name": "小张", "parent": "小红"},
                                        {"name": "小王", "parent": "小红"},
                                        {"name": "小程", "parent": "小红"},
                                        {"name": "小陈", "parent": "小红"},
                                        {"name": "小明", "parent": "小红"},
                                        {"name": "小张", "parent": "小红"},
                                        {"name": "小王", "parent": "小红"},
                                        {"name": "小程", "parent": "小红"},
                                        {"name": "小陈", "parent": "小红"},
                                        {"name": "程九", "parent": "程五"},
                                        {
                                            "name": "程十",
                                            "parent": "程五",
                                            "children": [
                                                {"name": "程十一", "parent": "程十"},
                                                {"name": "程十二", "parent": "程十"},
                                                {"name": "程十三", "parent": "程十"},
                                                {"name": "小张", "parent": "小红"},
                                                {"name": "小王", "parent": "小红"},
                                                {"name": "小程", "parent": "小红"},
                                                {"name": "小陈", "parent": "小红"},
                                                {"name": "小明", "parent": "小红"},
                                                {"name": "小张", "parent": "小红"},
                                                {"name": "小王", "parent": "小红"},
                                                {"name": "小程", "parent": "小红"},
                                                {"name": "小陈", "parent": "小红"},
                                                {"name": "小明", "parent": "小红"},
                                                {"name": "小张", "parent": "小红"},
                                                {"name": "小王", "parent": "小红"},
                                                {"name": "小程", "parent": "小红"},
                                                {"name": "小陈", "parent": "小红"},
                                                {"name": "小明", "parent": "小红"},
                                                {"name": "小张", "parent": "小红"},
                                                {"name": "小王", "parent": "小红"},
                                                {"name": "小程", "parent": "小红"},
                                                {"name": "小陈", "parent": "小红"},
                                            ]
                                        },
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "马一",
                    "parent": "李四",
                    "children": [
                        {"name": "马二", "parent": "马一"},
                        {"name": "马三", "parent": "马一"},
                        {"name": "马四", "parent": "马一"},
                        {"name": "马五", "parent": "马一"},
                        {"name": "马六", "parent": "马一"},
                        {"name": "马七", "parent": "马一"},
                        {"name": "小明", "parent": "小红"},
                        {"name": "小张", "parent": "小红"},
                        {"name": "小王", "parent": "小红"},
                        {"name": "小程", "parent": "小红"},
                        {"name": "小陈", "parent": "小红"},
                        {"name": "小明", "parent": "小红"},
                        {"name": "小张", "parent": "小红"},
                        {"name": "小王", "parent": "小红"},
                        {"name": "小程", "parent": "小红"},
                        {"name": "小陈", "parent": "小红"},
                        {"name": "小张", "parent": "小红"},
                        {"name": "小王", "parent": "小红"},
                        {"name": "小程", "parent": "小红"},
                        {"name": "小陈", "parent": "小红"},
                        {"name": "小明", "parent": "小红"},
                        {"name": "小张", "parent": "小红"},
                        {"name": "小王", "parent": "小红"},
                        {"name": "小程", "parent": "小红"},
                        {"name": "小陈", "parent": "小红"},
                        {"name": "小明", "parent": "小红"},
                        {"name": "小张", "parent": "小红"},
                        {"name": "小王", "parent": "小红"},
                        {"name": "小程", "parent": "小红"},
                        {"name": "小陈", "parent": "小红"},
                        {"name": "小明", "parent": "小红"},
                        {"name": "小张", "parent": "小红"},
                        {"name": "小王", "parent": "小红"},
                        {"name": "小程", "parent": "小红"},
                        {"name": "小陈", "parent": "小红"},
                        {"name": "小明", "parent": "小红"},
                        {"name": "小张", "parent": "小红"},
                        {"name": "小王", "parent": "小红"},
                        {"name": "小程", "parent": "小红"},
                        {"name": "小陈", "parent": "小红"},
                        {"name": "小明", "parent": "小红"},
                        {"name": "小张", "parent": "小红"},
                        {"name": "小王", "parent": "小红"},
                        {"name": "小程", "parent": "小红"},
                        {"name": "小陈", "parent": "小红"},
                    ]
                }
            ]
        },
        {
            "name": "小红",
            "parent": "张三",
            "children": [
                {"name": "小明", "parent": "小红"},
                {"name": "小张", "parent": "小红"},
                {"name": "小王", "parent": "小红"},
                {"name": "小程", "parent": "小红"},
                {"name": "小陈", "parent": "小红"},
                {"name": "小明", "parent": "小红"},
                {"name": "小张", "parent": "小红"},
                {"name": "小王", "parent": "小红"},
                {"name": "小程", "parent": "小红"},
                {"name": "小陈", "parent": "小红"},
                {"name": "小明", "parent": "小红"},
                {"name": "小张", "parent": "小红"},
                {"name": "小王", "parent": "小红"},
                {"name": "小程", "parent": "小红"},
                {"name": "小陈", "parent": "小红"},
                {"name": "小明", "parent": "小红"},
                {"name": "小张", "parent": "小红"},
                {"name": "小王", "parent": "小红"},
                {"name": "小程", "parent": "小红"},
                {"name": "小陈", "parent": "小红"},
                {"name": "小明", "parent": "小红"},
                {"name": "小张", "parent": "小红"},
                {"name": "小王", "parent": "小红"},
                {"name": "小程", "parent": "小红"},
                {"name": "小陈", "parent": "小红"},
                {"name": "小明", "parent": "小红"},
                {"name": "小张", "parent": "小红"},
                {"name": "小王", "parent": "小红"},
                {"name": "小程", "parent": "小红"},
                {"name": "小陈", "parent": "小红"},

            ]
        }
    ]
}];
